syntax = "Luau"
column_width = 100
line_endings = "Unix"
call_parentheses = "Always"
collapse_simple_statement = "ConditionalOnly"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
space_after_function_names = "Never"

[sort_requires]
enabled = true
